### ISSUE TITLE
status 503是什么意思，网络不好吗

### ISSUE THREAD

**Issue by lehahagirl** [MMF-FE/weex-http#2]
我们都不知道失败是什么状态，status 503是设么意思啊，谁有完整的status的状态，官网上啥也不写

**Comment by ciwyaitd** [comment]
@lehahagirl 
  - 1xx: Informational - Request received, continuing process

  - 2xx: Success - The action was successfully received,
    understood, and accepted

  - 3xx: Redirection - Further action must be taken in order to
    complete the request

  - 4xx: Client Error - The request contains bad syntax or cannot
    be fulfilled

  - 5xx: Server Error - The server failed to fulfill an apparently
    valid request
